apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: first-python-app
  template:
    metadata:
      labels:
        app: first-python-app
    spec:
      containers:
        - name: python-app
          image: mohitleo03/my-python-app
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: python-app
spec:
  selector:
    app: first-python-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer