apiVersion: v1
kind: Service
metadata: 
  name: hello-python-service
spec:
  selector:
    app: hello-python
  ports:
  - protocol: 'TCP'
    port: 5000
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hello-python
spec: 
  selector:
    matchLabels:
      app: hello-python
  replicas: 4
  template:
    metadata:
      labels: 
        app: hello-python
    spec: 
      containers:
      - name: hello-python
        image: mohitleo03/python-first-app
        imagePullPolicy: Never
        ports:
          containerPort: 5000