apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
      tier: backend
  spec:
    containers:
      - name: second-example
        image: mohitleo03/kub-first-app